// <auto-generated />
using System;
using FMA.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FMA.DAL.Migrations
{
    [DbContext(typeof(FootballMatchAppContext))]
    partial class FootballMatchAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FMA.DAL.Entities.Booking", b =>
                {
                    b.Property<Guid>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BookingTime")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<Guid>("MatchPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MatchRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PitchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("MatchPostId");

                    b.HasIndex("MatchRequestId");

                    b.HasIndex("PitchId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("FMA.DAL.Entities.MatchPost", b =>
                {
                    b.Property<Guid>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MatchTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PitchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PostById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PostByTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PostStatus")
                        .HasColumnType("int");

                    b.HasKey("PostId");

                    b.HasIndex("PitchId");

                    b.HasIndex("PostById");

                    b.HasIndex("PostByTeamId");

                    b.ToTable("MatchPosts");
                });

            modelBuilder.Entity("FMA.DAL.Entities.MatchRequest", b =>
                {
                    b.Property<Guid>("MatchRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DecisionTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MatchPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RequestById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RequestByTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RequestTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("MatchRequestId");

                    b.HasIndex("MatchPostId");

                    b.HasIndex("RequestById");

                    b.HasIndex("RequestByTeamId");

                    b.ToTable("MatchRequests");
                });

            modelBuilder.Entity("FMA.DAL.Entities.Pitch", b =>
                {
                    b.Property<Guid>("PitchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("PricePerHour")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("PitchId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Pitches");

                    b.HasData(
                        new
                        {
                            PitchId = new Guid("a2345678-90ab-cdef-1234-567890abcdef"),
                            ContactNumber = "0123456789",
                            Latitude = 10.762622,
                            Location = "Đại học Bách Khoa – Đại học Quốc gia TP.HCM, quận 10, Thành phố Hồ Chí Minh, Việt Nam.",
                            Longitude = 106.660172,
                            Name = "SAN BONG DA CUC KY DANG CAP",
                            OwnerId = new Guid("22345678-90ab-cdef-1234-567890abcdef"),
                            PricePerHour = 300m,
                            Status = 0
                        });
                });

            modelBuilder.Entity("FMA.DAL.Entities.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("11111111-2222-3333-4444-555555555555"),
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = new Guid("66666666-7777-8888-9999-000000000000"),
                            RoleName = "PitchOwner"
                        },
                        new
                        {
                            RoleId = new Guid("aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"),
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("FMA.DAL.Entities.Team", b =>
                {
                    b.Property<Guid>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamId");

                    b.HasIndex("CreatedById");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            TeamId = new Guid("23456789-0abc-def1-2345-67890abcdefa"),
                            CreatedById = new Guid("32345678-90ab-cdef-1234-567890abcdef"),
                            TeamName = "FPT FC"
                        },
                        new
                        {
                            TeamId = new Guid("b3456789-0abc-def1-2345-67890abcdefa"),
                            CreatedById = new Guid("42345678-90ab-cdef-1234-567890abcdef"),
                            TeamName = "Thunder FC"
                        });
                });

            modelBuilder.Entity("FMA.DAL.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("TeamMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TeamMemberId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            TeamMemberId = new Guid("62345678-90ab-cdef-1234-567890abcdef"),
                            JoinDate = new DateTime(1990, 1, 1, 7, 0, 0, 0, DateTimeKind.Local),
                            Position = "Forward",
                            TeamId = new Guid("23456789-0abc-def1-2345-67890abcdefa")
                        },
                        new
                        {
                            TeamMemberId = new Guid("72345678-90ab-cdef-1234-567890abcdef"),
                            JoinDate = new DateTime(1990, 1, 1, 7, 0, 0, 0, DateTimeKind.Local),
                            Position = "Midfielder",
                            TeamId = new Guid("23456789-0abc-def1-2345-67890abcdefa")
                        },
                        new
                        {
                            TeamMemberId = new Guid("82345678-90ab-cdef-1234-567890abcdef"),
                            JoinDate = new DateTime(1990, 1, 1, 7, 0, 0, 0, DateTimeKind.Local),
                            Position = "Defender",
                            TeamId = new Guid("b3456789-0abc-def1-2345-67890abcdefa")
                        });
                });

            modelBuilder.Entity("FMA.DAL.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("12345678-90ab-cdef-1234-567890abcdef"),
                            Address = "123 Admin Street, Admin City, Admin Country",
                            Email = "admin@gmail.com",
                            PasswordHash = "$2a$11$rTz6DZiEeBqhVrzF25CgTOBPf41jpn2Tg/nnIqnX8KS6uIerB/1dm",
                            PhoneNumber = "0123456789",
                            RoleId = new Guid("11111111-2222-3333-4444-555555555555"),
                            Username = "admin"
                        },
                        new
                        {
                            UserId = new Guid("22345678-90ab-cdef-1234-567890abcdef"),
                            Address = "456 Pitch Owner Street, Pitch Owner City, Pitch Owner Country",
                            Email = "pitchowner@gmail.com",
                            PasswordHash = "$2a$11$rTz6DZiEeBqhVrzF25CgTOBPf41jpn2Tg/nnIqnX8KS6uIerB/1dm",
                            PhoneNumber = "0987654321",
                            RoleId = new Guid("66666666-7777-8888-9999-000000000000"),
                            Username = "pitchowner"
                        },
                        new
                        {
                            UserId = new Guid("32345678-90ab-cdef-1234-567890abcdef"),
                            Address = "789 User1 Street, User1 City, User1 Country",
                            Email = "user-1@gmail.com",
                            PasswordHash = "$2a$11$rTz6DZiEeBqhVrzF25CgTOBPf41jpn2Tg/nnIqnX8KS6uIerB/1dm",
                            PhoneNumber = "1234567890",
                            RoleId = new Guid("aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"),
                            Username = "user1"
                        },
                        new
                        {
                            UserId = new Guid("42345678-90ab-cdef-1234-567890abcdef"),
                            Address = "101 User2 Street, User2 City, User2 Country",
                            Email = "user-2@gmail.com",
                            PasswordHash = "$2a$11$rTz6DZiEeBqhVrzF25CgTOBPf41jpn2Tg/nnIqnX8KS6uIerB/1dm",
                            PhoneNumber = "1234567890",
                            RoleId = new Guid("aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"),
                            Username = "user2"
                        },
                        new
                        {
                            UserId = new Guid("52345678-90ab-cdef-1234-567890abcdef"),
                            Address = "102 User3 Street, User3 City, User3 Country",
                            Email = "user-3@gmail.com",
                            PasswordHash = "$2a$11$rTz6DZiEeBqhVrzF25CgTOBPf41jpn2Tg/nnIqnX8KS6uIerB/1dm",
                            PhoneNumber = "1234567890",
                            RoleId = new Guid("aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"),
                            Username = "user3"
                        });
                });

            modelBuilder.Entity("FMA.DAL.Entities.UserToken", b =>
                {
                    b.Property<Guid>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("TokenKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TokenId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("FMA.DAL.Entities.Booking", b =>
                {
                    b.HasOne("FMA.DAL.Entities.MatchPost", "MatchPost")
                        .WithMany()
                        .HasForeignKey("MatchPostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FMA.DAL.Entities.MatchRequest", "MatchRequest")
                        .WithMany()
                        .HasForeignKey("MatchRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FMA.DAL.Entities.Pitch", "Pitch")
                        .WithMany("Bookings")
                        .HasForeignKey("PitchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MatchPost");

                    b.Navigation("MatchRequest");

                    b.Navigation("Pitch");
                });

            modelBuilder.Entity("FMA.DAL.Entities.MatchPost", b =>
                {
                    b.HasOne("FMA.DAL.Entities.Pitch", "Pitch")
                        .WithMany("MatchPosts")
                        .HasForeignKey("PitchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FMA.DAL.Entities.User", "PostBy")
                        .WithMany()
                        .HasForeignKey("PostById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FMA.DAL.Entities.Team", "PostByTeam")
                        .WithMany()
                        .HasForeignKey("PostByTeamId");

                    b.Navigation("Pitch");

                    b.Navigation("PostBy");

                    b.Navigation("PostByTeam");
                });

            modelBuilder.Entity("FMA.DAL.Entities.MatchRequest", b =>
                {
                    b.HasOne("FMA.DAL.Entities.MatchPost", "MatchPost")
                        .WithMany("MatchRequests")
                        .HasForeignKey("MatchPostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FMA.DAL.Entities.User", "RequestBy")
                        .WithMany()
                        .HasForeignKey("RequestById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FMA.DAL.Entities.Team", "RequestByTeam")
                        .WithMany()
                        .HasForeignKey("RequestByTeamId");

                    b.Navigation("MatchPost");

                    b.Navigation("RequestBy");

                    b.Navigation("RequestByTeam");
                });

            modelBuilder.Entity("FMA.DAL.Entities.Pitch", b =>
                {
                    b.HasOne("FMA.DAL.Entities.User", "User")
                        .WithMany("Pitchs")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FMA.DAL.Entities.Team", b =>
                {
                    b.HasOne("FMA.DAL.Entities.User", "CreateBy")
                        .WithMany("Teams")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreateBy");
                });

            modelBuilder.Entity("FMA.DAL.Entities.TeamMember", b =>
                {
                    b.HasOne("FMA.DAL.Entities.Team", "Team")
                        .WithMany("TeamMembers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FMA.DAL.Entities.User", b =>
                {
                    b.HasOne("FMA.DAL.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FMA.DAL.Entities.UserToken", b =>
                {
                    b.HasOne("FMA.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FMA.DAL.Entities.MatchPost", b =>
                {
                    b.Navigation("MatchRequests");
                });

            modelBuilder.Entity("FMA.DAL.Entities.Pitch", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("MatchPosts");
                });

            modelBuilder.Entity("FMA.DAL.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("FMA.DAL.Entities.Team", b =>
                {
                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("FMA.DAL.Entities.User", b =>
                {
                    b.Navigation("Pitchs");

                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
